### ISSUE TITLE
Uncaught NumberFormatException on "Add Score" dialog's +1/Undo Buttons

### ISSUE THREAD

**Issue by wheerdam** [wheerdam/merccc#8]
If the user has a score with +1/Undo score type and typed in an invalid number in the "Add Score" dialog, clicking on either the +1 or Undo button will cause an uncaught NumberFormatException:

```
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "2.0z"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.osumercury.controlcenter.gui.ControlFrame$ScoringUpUndoActionListener.actionPerformed(ControlFrame.java:1420)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
...
```
The "Add Score" dialog is the only place where this is possible since the score text field would not be user-editable otherwise.

**Comment by wheerdam** [comment]
Fixed in 1.4.1
